### ISSUE TITLE
ulx3s script

### ISSUE THREAD

**Issue by arblake** [rob-ng15/Silice-Playground#11]
You have a compile script to create J1eforth for the FOMU but I cannot find one for the ULX3S  device, or have I missed it?

**Comment by rob-ng15** [comment]
It uses the Silice build system, go into the ulx3s directory and type

make ulx3s

Instructions are in the readme I believe.

**Comment by rob-ng15** [comment]
I've got some changes to copy over from the risc-ice-v project that solve
one or two issues.

**Comment by rob-ng15** [comment]
Closing, not an issue with this project.
