### ISSUE TITLE
build j1eforth on ulx3s

### ISSUE THREAD

**Issue by arblake** [rob-ng15/Silice-Playground#12]
Build almost complete to this point:
2.32.1. Executing OPT_EXPR pass (perform const folding).
Optimizing module top.
/usr/local/frameworks/boards/ulx3s/ulx3s.sh: line 35: 48322 Killed                  yosys -p 'scratchpad -copy abc9.script.flow3 abc9.script; synth_ecp5 -abc9 -json build.json' build.v
ERROR: Failed to open JSON file 'build.json'.
0 warnings, 1 error
sed: can't read build.config: No such file or directory

command was:  sudo make ulx3s
I can build and install "blinky" in Silice

**Comment by rob-ng15** [comment]
There is an issue with the updated yosys that @sylefeb is working through.

**Comment by rob-ng15** [comment]
I haven't yet updated j1eforth for the changes that are required. I'll look
tomorrow.

**Comment by arblake** [comment]
Do not disturb your Sunday family activities for me.

**Comment by rob-ng15** [comment]
Changes made and tested with yosys r10262 and r10391.

Please update your Silice to the DRAFT branch (if you get complaints about simple_dualport_bram then Silice hasn't been updated).

Closing as working.
