### ISSUE TITLE
J1eforth on ULX3S, not OK prompt

### ISSUE THREAD

**Issue by arblake** [rob-ng15/Silice-Playground#13]
Rob,
I have been busy with other things, 
Updated software here and attempted a build. It completed and loaded onto device. No OK prompt.
Could it be a Silice or yosys problem or something else?
I did log the build process. Attached. big
Adrian
[log.txt](https://github.com/rob-ng15/Silice-Playground/files/5997177/log.txt)

**Comment by rob-ng15** [comment]
Hmmm,

Just flashed the build that is based on the latest code in github, and it
gives me the prompt. I'm not expert enough to go through the logs sadly. I
have a few more changes to make to the code, from PAWS (the Risc-V
processor). I'll port those across soon.

Rob.

**Comment by arblake** [comment]
I just updated software and rebuilt .... no prompt. I can load a build done on 20th January and it works.
total 59532
-rw-r--r-- 1 root root  1212090 Feb 17 19:27 build.bit
-rw-r--r-- 1 root root 15632187 Feb 17 19:27 build.config
-rw-r--r-- 1 root root 40738182 Feb 17 19:16 build.json
-rw-r--r-- 1 root root  2548135 Feb 17 19:27 build.svf
-rw-r--r-- 1 root root   819586 Feb 17 19:12 build.v
The bit file looks small

**Comment by rob-ng15** [comment]
Ok, I'm just working on PAWS at the moment. I'll look soon. Probably
another yosys issue!

**Comment by arblake** [comment]
Rob
Yosys 0.9+3819 (git sha1 48d0aeb0, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os)
silice  version: 0.1

**Comment by rob-ng15** [comment]
Hi there,

Not sure what went wrong, but I have reverted the last changes and now
compiles. Will look again at it later. Thanks for pointing this out.

Rob.

**Comment by arblake** [comment]
Now it does not build:
 dualport_bram_wenable1_type =                           uint
----------<<<<< error >>>>>----------

=> file: /home/adrian/Silice-Playground/j1eforth/DE10NANO-ULX3S/ULX3S/../j1eforth.ice
=> line: 37


<<<<<<< HEAD
^^^ surprised to find this here

error: [syntax error]

 /----------------------------------------------------------------------------\
 |                                                                            |
 |  yosys -- Yosys Open SYnthesis Suite

**Comment by arblake** [comment]
Rob,
Looks like your editing added in some bad lines and drop others

**Comment by rob-ng15** [comment]
My apologies, it was from the reverting.

**Comment by arblake** [comment]
Now this,
=> file: /home/adrian/Silice-Playground/j1eforth/DE10NANO-ULX3S/ULX3S/../tile_map.ice
=> line: 73


tilemapentry(tiles.rdata0).tilenumber
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ unkown bitfield 'tilemapentry'

error: Silice compiler stopped

**Comment by rob-ng15** [comment]
I'm catching up! There is a slight mismatch between the old and new systems.

I've got it building here. The sprite update flag system is different, so
the asteroids will be a bit out of sync until I can recalculate them. I'll
do it soon. Look for the next update which will hopefully be in the next 5
minutes and all should be good.

Rob.

**Comment by rob-ng15** [comment]
Hi Adrian,

Just posting now! Not sure why it wasn't working, but I've backported the
changes from PAWS and made a few slight adjustments. I have a few more,
which I'll try and get around to later today.

Rob.

**Comment by arblake** [comment]
Rob,
I understand that you probably have other things to do.  Later in the day is ok

**Comment by rob-ng15** [comment]
Sorry it has done it again and plastered HEAD things all over the place!

**Comment by rob-ng15** [comment]
Right it seems to have uploaded correctly this time. Let me know how you
get on.

Rob.

**Comment by arblake** [comment]
Better but not perfect.  investigating

**Comment by rob-ng15** [comment]
How do you mean?

**Comment by arblake** [comment]
Rob,
My build get this far:
2.44.15.2. Executing ABC9_OPS pass (helper functions for ABC9).

2.44.15.3. Executing XAIGER backend.
ERROR: Assert `!aig_map.count(bit)' failed in backends/aiger/xaiger.cc:435.
ERROR: Failed to open JSON file 'build.json'.
0 warnings, 1 error
sed: can't read build.config: No such file or directory
Failed to open input file
ULX2S / ULX3S JTAG programmer v4.8 (git cc3ea93 built Dec  3 2020 08:47:16)

It is a pathing problem
Trying to resolve.

**Comment by rob-ng15** [comment]
Hi Adrian,

I am on

`
[rob@ArchLinux ULX3S]$ yosys --version
Yosys 0.9+3833 (git sha1 b0004911c, gcc 10.2.0 -march=x86-64 -mtune=generic
-O2 -fno-plt -fPIC -Os)
`

and it is building fine. So not sure.

Rob.

**Comment by arblake** [comment]
yosys --version
Yosys 0.9+3911 (git sha1 127484e6, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os)

Not much difference

**Comment by rob-ng15** [comment]
yosys after yosys-git-0.9+3833.r10478.b0004911c-1-x86_64.pkg.tar.zst and before yosys-git-0.9+3905.r10550.4e741adda-1-x86_64.pkg.tar.zst has a change that stops the build.

I am not skilled enough in this area to help with the debug, so have stuck to yosys-git-0.9+3833.r10478.b0004911c-1-x86_64.pkg.tar.zst until the issue can be resolved.

Rob.

**Comment by arblake** [comment]
Rob,
I understand. I am not skilled in git. How can I get yosys-git-0.9+3833.r10478.b0004911c-1-x86_64.pkg.tar.zst  ?
Adrian

**Comment by rob-ng15** [comment]
That is an ArchLinux package.

**Comment by arblake** [comment]
I have ubuntu   so I must wait until the problem is resolved.

**Comment by rob-ng15** [comment]
Hi Adrian,

I've been trying updated versions of yosys to see if they fix this particular issue, and with build 0.9+4052.r10702.0ccc7229c-1 j1eforth builds again for the ulx3s.

**Comment by arblake** [comment]
Starting from beginning again. Reloading all software.
